Add krpintf

diff --git a/kernel/get-deps b/kernel/get-deps
--- a/kernel/get-deps
+++ b/kernel/get-deps
@@ -8,43 +8,48 @@ test -z "$srcdir" && srcdir=.
 cd "$srcdir"
 
 clone_repo_commit() {
-    if test -d "$2/.git"; then
-        git -C "$2" reset --hard
-        git -C "$2" clean -fd
-        if ! git -C "$2" -c advice.detachedHead=false checkout $3; then
-            rm -rf "$2"
-        fi
-    else
-        if test -d "$2"; then
-            echo "error: '$2' is not a Git repository" 1>&2
-            exit 1
-        fi
-    fi
-    if ! test -d "$2"; then
-        git clone $1 "$2"
-        if ! git -C "$2" -c advice.detachedHead=false checkout $3; then
-            rm -rf "$2"
-            exit 1
-        fi
-    fi
+	if test -d "$2/.git"; then
+		git -C "$2" reset --hard
+		git -C "$2" clean -fd
+		if ! git -C "$2" -c advice.detachedHead=false checkout $3; then
+			rm -rf "$2"
+		fi
+	else
+		if test -d "$2"; then
+			echo "error: '$2' is not a Git repository" 1>&2
+			exit 1
+		fi
+	fi
+	if ! test -d "$2"; then
+		git clone $1 "$2"
+		if ! git -C "$2" -c advice.detachedHead=false checkout $3; then
+			rm -rf "$2"
+			exit 1
+		fi
+	fi
 }
 
 rm -f .deps-obtained
 
 clone_repo_commit \
-    https://codeberg.org/OSDev/freestnd-c-hdrs-0bsd.git \
-    freestnd-c-hdrs \
-    097259a899d30f0a4b7a694de2de5fdda942e923
+	https://codeberg.org/OSDev/freestnd-c-hdrs-0bsd.git \
+	freestnd-c-hdrs \
+	097259a899d30f0a4b7a694de2de5fdda942e923
 
 clone_repo_commit \
-    https://codeberg.org/OSDev/cc-runtime.git \
-    cc-runtime \
-    dae79833b57a01b9fd3e359ee31def69f5ae899b
+	https://codeberg.org/OSDev/cc-runtime.git \
+	cc-runtime \
+	dae79833b57a01b9fd3e359ee31def69f5ae899b
 
 clone_repo_commit \
-    https://codeberg.org/Limine/limine-protocol.git \
-    limine-protocol \
-    26519f1b598564db409e50d1d84eb30642d58ba3
+	https://codeberg.org/Limine/limine-protocol.git \
+	limine-protocol \
+	26519f1b598564db409e50d1d84eb30642d58ba3
+
+clone_repo_commit \
+	https://github.com/mintsuki/flanterm.git \
+	flanterm \
+	b5038e828de1dc6c049222a3c1670f7976e6c5a3
 
 touch .deps-obtained
 
